CREATE TABLE ongs(
id_ongs INT PRIMARY KEY AUTO_INCREMENT,
email_ong VARCHAR(200) NOT NULL,
phone_ong INT NOT NULL
);

CREATE TABLE users(
id_user INT PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(200) NOT NULL,
phone INT NOT NULL
);

